<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>JQVMap - World Map</title>
    
    <link href="View/css/style.css" media="screen" rel="stylesheet" type="text/css" />
    
    <link href="utils/js/jqvmap/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    <script src="utils/js/jqvmap/jquery.vmap.js" type="text/javascript"></script>
    <script src="utils/js/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
	<script src="utils/js/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
    
	<script type="text/javascript">
	jQuery(document).ready(function() {
                $("#vmap").css({"height":$(window).height()-75});
		jQuery('#vmap').vectorMap({
		    map: 'world_en',
		    backgroundColor: '#cfe2f3',
		    color: '#ffffff',
		    hoverOpacity: 0.7,
		    selectedColor: '#666666',
		    enableZoom: true,
		    showTooltip: true,
		    values: sample_data,
		    scaleColors: ['#42afe0', '#006491'],
		    normalizeFunction: 'polynomial',
                     onRegionClick: function(element, code, region)
                        {
                            var message = 'You clicked "'
                                + region 
                                + '" which has the code: '
                                + code.toUpperCase();

                            alert(message);
                        },
                         onLabelShow: function(event, label, code)
                        {

                                label.html(label.text() + '<br/>-- université(s)');

                        }
		});
                
                $(window).resize(function() {
                   $("#vmap").css({"height":$("#global").height()-75}); 
                });
	});
	</script>
  </head>
  <body>
      <div id="global">
          <div id="header">
              <a id="button_subscribe" class="button" href="#">Inscription</a>
              <a id="button_connexion" class="button" href="#">Connexion</a>
          </div>
        <div id="vmap" style="width: 100%; height: 100%;"></div>
      </div>
  </body>
</html>
